# site settings
title: CCP
subtitle:
email: maltman333@gmail.com
description: Our goal is to help business owners achieve liquidity and lead businesses to bright and successful futures. 
baseurl: # the subpath of your site, e.g. /blog
url: continuitycapitalpartners.com # the base hostname & protocol for your site
author:
street_address: 
city: New York
state: New York
zip_code: 
country: 
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 7

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
